### ISSUE TITLE
Connect error: Connection refused (111)

### ISSUE THREAD

**Issue by powermx** [Bonveio/BonvScripts#2]
Hello, i just installed DebianOCS-Panel

After add an user from panel, I login normal, and user's panel i tried to Create account, but i received : Connect error: Connection refused (111)

I also checked Server passwd was correct and all input data, but i still received that error.

How could i fix it ?

**Comment by Bonveio** [comment]
OCS Panel relies on webmin. You need to install webmin first on your server and open 10000/tcp on your firewall (Also, configure webmin to listen and accept http connections). You can install it manually using a .deb package or just running DebianVPS-Installer for complete vpn server setup
